// Code generated by egtool pioasm; DO NOT EDIT.

package main

import "github.com/embeddedgo/pico/hal/pio"

/// Global symbols ///
const (
)

/// Program rtc6715spi ///

// Symbols
const (
)

// Labels
const (
)

// Code
const pioProg_rtc6715spi pio.StringProgram = "" +
	"\xff" + //             origin:    -1
	"\x00\x01\x00" + //     CLKDIV:    1
	"\x60\x50\x01\x40" + // EXECCTRL:  sideset=opt wrap=0-21
	"\x01\x00\x0d\x00" + // SHIFTCTRL: fifo=txrx out=,right,32 in=1,right,32,auto
	"\x10\x44" + //         PINCTRL:   sideset=2 set=1 out=1
	// Instructions:
	//              .wrap_target
	"\x01\xe0" + //  0:  set    pins, 1
	"\x00\xe0" + //  1:  set    pins, 0
	"\x00\x00" + //  2:  jmp    0
	"\x01\xe0" + //  3:  set    pins, 1
	"\x6b\xa0" + //  4:  mov    pindirs, ~null
	"\xa0\x80" + //  5:  pull   block
	"\x00\xe0" + //  6:  set    pins, 0
	"\x21\x60" + //  7:  out    x, 1
	"\x2d\x00" + //  8:  jmp    !x, 13
	"\x58\xe0" + //  9:  set    y, 24
	"\x01\x70" + // 10:  out    pins, 1         side 0
	"\x8a\x18" + // 11:  jmp    y--, 10         side 1
	"\x03\x10" + // 12:  jmp    3               side 0
	"\x44\xe0" + // 13:  set    y, 4
	"\x01\x70" + // 14:  out    pins, 1         side 0
	"\x8e\x18" + // 15:  jmp    y--, 14         side 1
	"\x63\xa0" + // 16:  mov    pindirs, null
	"\x52\xf0" + // 17:  set    y, 18           side 0
	"\x01\x58" + // 18:  in     pins, 1         side 1
	"\x92\x10" + // 19:  jmp    y--, 18         side 0
	"\x01\x40" + // 20:  in     pins, 1
	"\x6c\x40" + // 21:  in     null, 12
	//              .wrap
	""
